### ISSUE TITLE
The module TextInputHighlightModule can not be loaded in a shared module

### ISSUE THREAD

**Issue by GitHubish** [mattlewis92/angular-text-input-highlight#1]
Hi, I can not load the module in a shared module, the component is not found. Do you have an idea ?

**Comment by mattlewis92** [comment]
Sorry I have no idea, do you have a minimal stackblitz or something that reproduces your problem?

**Comment by mattlewis92** [comment]
Closing due to lack of response, happy to help debug more with a repro though!
