### ISSUE TITLE
Is there a way to force a re-render on tags?

### ISSUE THREAD

**Issue by nicktobolski** [mattlewis92/angular-text-input-highlight#3]
Hello and thanks for this module!

I'm using in a bit differently and running into an issue: 

Instead of calling my `addTags()` method via the `(input)` directive on my `<textarea>` (e.g. `(input)="addTags()"`, I' using an intermediary method where the user will highlight some text, make some choices, and upon which I programmatically call `addTags()` for the `<textarea>`.

In this case, the tag isn't displayed until I manually edit the `<textarea>`'s value (`patchValue` didn't seem to trigger a change detection/re-rendering of the tags).

This being the case, is there a method I can call to force this module to re-render the tags? Or can you otherwise advise on a solution to this issue?

**Comment by mattlewis92** [comment]
Hi there, you can use the [`refresh`](https://github.com/mattlewis92/angular-text-input-highlight/commit/da95817) method on the component to force it to re-render.

```
<mwl-text-input-highlight #textInputHighlight>
</mwl-text-input-highlight>
<button (click)="textInputHighlight.refresh()">Refresh</button>
```


Hope that helps! 😄

**Comment by mattlewis92** [comment]
Can you make a stackblitz or something else that I can run to debug more? Thanks! 😄

**Comment by mattlewis92** [comment]
Ah right, that makes sense. `.push` doesn't create a new array, and angular doesn't do deep watching of objects and arrays so it never picks up the change. You need to make a new instance of the array in order to trigger change detection. You can do this in a number of ways:
```
const tags = ['foo'];
const clone1 = [...tags];
const clone2 = Array.from(tags);
const clone3 = [].concat(tags);
```

Hope that helps! 😄

**Comment by nicktobolski** [comment]
Very, very, very helpful. Thanks!!
